config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resources :books do
    collection do
      get :search
    end
  end
  devise_for :users, only: [:sessions, :registrations]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  update_index("books") { self }

  has_one_attached :cover, dependent: :destroy
  has_one_attached :content, dependent: :destroy

  validates :title, presence: true
  validates :author, presence: true
  validates :isbn, presence: true

  scope :ordered, -> { order("title") }

  def self.filtered_books?(books)
    books.count < Book.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = collection
  end

  def new
    @book = Book.new
  end

  def show
    @book = resourse
  end

  def edit
    @book = resourse
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path, notice: "Book was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @book = resourse

    if @book.update(book_params)
      redirect_to @book, notice: "Book was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    resourse.destroy

    redirect_to books_path, alert: "Book was successfully destroyed.", status: :see_other
  end

  def search
    book_searcher = BookSearch.instance
    search_results = book_searcher.search (params[:search][:query])
    @books = search_results 
    flash.now[:notice] = "Books found: #{search_results.count}"

    render :index
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :isbn, :description, :cover, :content, :search)
  end

  def collection
    Book.ordered
  end

  def resourse
    collection.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book.html.erb
<div class="form">
  <div id="<%= dom_id book %>" class="flex">
    <%= image_tag book.cover, class: "h-96 p-2" if book.cover.attached? %>
    <div class="book-details">
      <p class="my-5">
        <strong class="block font-medium mb-1">Title:</strong>
        <div class="book-show">
          <%= book.title %>
        </div>
      </p>
      <p class="my-5">
        <strong class="block font-medium mb-1">Author:</strong>
        <div class="book-show">
          <%= book.author %>
        </div>
      </p>
      <p class="my-5">
        <strong class="block font-medium mb-1">Isbn:</strong>
        <div class="book-show">
          <%= book.isbn %>
        </div>
      </p>
      <p class="my-5">
        <strong class="block font-medium mb-1">Description:</strong>
        <div class="book-show">
          <%= book.description %>
        </div>
      </p>
    </div>
  </div>

  <div class="flex">
    <%= link_to "Read book", reader_book_path(book), class: "btn-primary" if book.content.attached? %>
    <% if user_signed_in? %>
      <%= link_to "Edit this book", edit_book_path(book), class: "btn-gray" %>
      <%= button_to "Destroy this book", book_path(book), method: :delete, class: "btn-red" %>
    <% end %>
    <%= link_to "Back to books", books_path, class: "btn-gray" %>
  </div>
</div>

app/views/books/_cover.html.erb
<%= link_to book_path(book) do %>
  <div class="book-item relative">
    <div id="<%= dom_id book %>">
      <% if book.cover.attached? %>
        <%= image_tag book.cover %>
      <% else %>
        <%= image_tag "book_cover.png" %>
        <p class="book-title">
          <%= book.title %>
        </p>
        <p class="book-author">
          <%= book.author %>
        </p>
        <p class="book-isbn">
          IBSN: <%= book.isbn %>
        </p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/books/_form.html.erb
<div class="form">
  <%= simple_form_for book, url: polymorphic_path(book), defaults: { input_html: { class: "w-full" } } do |f| %>
    <div class="my-5">
      <%= f.input :title %>
    </div>
    <div class="my-5">
      <%= f.input :author %>
    </div>
    <div class="my-5">
      <%= f.input :isbn %>
    </div>
    <div class="my-5">
      <%= f.input :description %>
    </div>
    <%= f.input :cover, as: :file %>
    <%= f.input :content, as: :file %>
    <div class="flex">
      <%= f.button :submit, class: "btn-gray" %>
      <%= link_to "Back to books", books_path, class: "btn-gray" %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing book</h1>
  <%= render "books/form", book: @book %>
</div>

app/views/books/index.html.erb
<div class="w-full">
  <div class="flex items-center">
    <h1 class="font-bold text-4xl">List of books</h1>

    <search class="ml-auto flex space-x-4 m-2">
      <%= simple_form_for :search, url: search_books_path, method: :get do |f| %>
        <div class="flex items-center space-x-2">
          <%= f.input :query, as: :search, input_html: { placeholder: "Search in library..." }, label: false %>
          <%= f.submit "Search", class: "btn-gray" %>
        </div>
      <% end %>
    </search>
    <% if (Book.filtered_books?(@books)) %>
      <%= link_to "Back to all books", books_path, class: "btn-gray" %>
    <% end %>  
    <% if user_signed_in? %>
      <%= link_to "New book", new_book_path, class: "btn-primary" %>
    <% end %>
  </div>

  <div class="books-list">
    <%= render partial: "books/cover", collection: @books, as: :book %>
  </div>
</div>

app/views/books/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New book</h1>
  <%= render "books/form", book: @book %>
</div>

app/views/books/reader.html.erb
<div class="flex"> 
<h1 class="fixed left-0 font-bold text-4xl w-64"><%= @book.title %> </h1> 
  <div id="adobe-dc-view" data-controller="adobe-viewer" 
                          data-adobe-viewer-url="<%= rails_blob_path(@book.content, only_path: true) %>" 
                          data-adobe-viewer-filename="<%= @book.content.filename %>"
                          data-adobe-viewer-element-id="adobe-dc-view">
  </div>
  <%= link_to "Back to books", books_path, class: "fixed right-0 btn-gray" %>
</div>

app/views/books/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Show book</h1>

  <%= render "books/book", book: @book %>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="flash-base flash-<%= type %>">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="flex justify-between flex text-center items-center">
    <div></div> <!-- empty block for centering text -->
      <% if user_signed_in? %>
        <%= "#{current_user.first_name}, welcome to BookHub!" %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn-gray" %>
      <% else %>
        Welcome to BookHub!
        <%= link_to "Login", new_user_session_path, class: "btn-gray" %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BookHub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://acrobatservices.adobe.com/view-sdk/viewer.js"></script>
  </head>
  <body>

    <%= render "layouts/header" %>

    <div>
      <main class="container">
        <%= render "layouts/flash" %>
        <%= yield %>
      </main>
    </div>

    <footer>
        BookHub &copy; 2023
    </footer>
  </body>
</html>